server:
  affinity: ''
  # ui:
  #   enabled: true
  #   serviceType: LoadBalancer
  # dev:
  #   enabled: true
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        cluster_name = "vault-integrated-storage"
        ui = true

        storage "raft" {
           path = "/vault/data/"
        }

        listener "tcp" {
           address = "[::]:8200"
           cluster_address = "[::]:8201"
           tls_disable = "true"
        }
        
        service_registration "kubernetes" {}
